# Yoink ideas from Godot's issue template
# https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

contact_links:
  - name: Lore proposals
    url: https://github.com/Perkedel/After-Church/issues
    about: Please submit lore proposals on the After Church repository, not here.
  
  - name: Kade Engine issues (unavailable due to communities trouble)
    url: https://github.com/KadeDev/Kade-Engine/issues
    about: Please submit report if this the issue mainly goes to Kade Engine itself. uh, rest well, Kade. (no, he's still alive & well)

  - name: JOELwindows7 Contact Collections
    url: https://cointr.ee/joelwindows7
    about: Joel's account collection. Please refrain from talking personal drama issue unless if it is about a lore & it's publicly affects fans of it.
  
   