name: CI-bigMakku

# Controls when the workflow will run
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: krdlab/setup-haxe@v1.1.6
        with:
          haxe-version: 4.2.3
      - run: |
          haxe -version
          haxelib install hxnodejs
