jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: krdlab/setup-haxe
        with:
          haxe-version: 4.2.3
      - run: |
          haxe -version
          haxelib install hxnodejs
